local ITEM = Clockwork.item:New("weapon_base");
	ITEM.name = "M4A1";
	ITEM.cost = 300;
	ITEM.model = "models/weapons/w_rif_m4a1.mdl";
	ITEM.weight = 2;
	ITEM.access = "V";
	ITEM.uniqueID = "rcs_m4a1";
	ITEM.business = true;
	ITEM.description = "An old earth weapon. Looks like an assault rifle.";
	ITEM.isAttachment = true;
	ITEM.loweredOrigin = Vector(3, 0, -4);
	ITEM.loweredAngles = Angle(0, 45, 0);
	ITEM.attachmentBone = "ValveBiped.Bip01_Pelvis";
	ITEM.attachmentOffsetAngles = Angle(-180, 180, 90);
	ITEM.attachmentOffsetVector = Vector(-4.19, 0, -8.54);
ITEM:Register();